/**
 * finds.js — Mug Guy "other finds" inventory
 *
 * Same structure as mugs.js. To add a new find:
 *   1. Copy one of the objects below
 *   2. Give it a unique id
 *   3. Fill in your details
 *   4. Set imgs to array of paths in img/finds/
 *   5. Paste your eBay listing URL into ebayUrl
 *   6. Set sold: true once it sells
 *
 * Types: art | book | watch | plate | vessel | clothing | electronics | other
 */

const FINDS = [
  {
    id: 1,
    name: "Syracuse China Diner Plate",
    era: "1970s",
    type: "plate",
    price: 12,
    imgs: ["img/finds/plate.syracuse-china.white.green.jpg"],
    emoji: "🍽️",
    badge: "rare",
    sold: false,
    ebayUrl: "https://www.ebay.com/itm/YOUR_LISTING_ID",
    added: "2025-12-31",
    description: "",
  },
  {
    id: 2,
    name: "Speckled Diner Plate",
    era: "1980s",
    type: "plate",
    price: 8,
    imgs: ["img/finds/plate.speckled-diner.cream.brown.jpg"],
    emoji: "🍽️",
    badge: null,
    sold: false,
    ebayUrl: "https://www.ebay.com/itm/YOUR_LISTING_ID",
    added: "2025-12-31",
    description: "",
  },
  {
    id: 3,
    name: "Vintage Poetry Book Set w/ Bookends",
    era: "Early 1900s",
    type: "book",
    price: 45,
    imgs: ["img/finds/books.vintage-poetry-set.blue.brown.jpg"],
    emoji: "📚",
    badge: "rare",
    sold: false,
    ebayUrl: "https://www.ebay.com/itm/YOUR_LISTING_ID",
    added: "2026-02-07",
    description: "",
  },
  {
    id: 4,
    name: "Gruen Classic Dual-Dial Watch",
    era: "1990s",
    type: "watch",
    price: 55,
    imgs: ["img/finds/watch.gruen-classic-dual-dial.gold.black.jpg"],
    emoji: "⌚",
    badge: null,
    sold: false,
    ebayUrl: "https://www.ebay.com/itm/YOUR_LISTING_ID",
    added: "2026-02-08",
    description: "",
  },
  {
    id: 5,
    name: "Hand-Painted Floral Porcelain Plate",
    era: "Early 1900s",
    type: "plate",
    price: 18,
    imgs: ["img/finds/plate.hand-painted-floral.white.purple.jpg"],
    emoji: "🌸",
    badge: "rare",
    sold: false,
    ebayUrl: "https://www.ebay.com/itm/YOUR_LISTING_ID",
    added: "2026-02-09",
    description: "",
  },
  {
    id: 6,
    name: "Peanuts Snoopy & Woodstock Plate",
    era: "2000s",
    type: "plate",
    price: 10,
    imgs: ["img/finds/plate.peanuts-snoopy.blue.white.jpg"],
    emoji: "🐶",
    badge: null,
    sold: false,
    ebayUrl: "https://www.ebay.com/itm/YOUR_LISTING_ID",
    added: "2026-02-09",
    description: "",
  },
  {
    id: 7,
    name: "Tiosa by International Silver Vessel",
    era: "1990s",
    type: "vessel",
    price: 22,
    imgs: ["img/finds/vessel.tiosa-international-silver.silver.silver.jpg"],
    emoji: "🏺",
    badge: null,
    sold: false,
    ebayUrl: "https://www.ebay.com/itm/YOUR_LISTING_ID",
    added: "2026-02-09",
    description: "",
  },
  {
    id: 8,
    name: "Handmade Angel Christmas Ornaments — Set of 2 with Gift Box",
    era: "Vintage",
    type: "holiday",
    price: 10,
    imgs: ["img/finds/ornament.avon.crochet.two.angels.jpg"],
    emoji: "👼",
    badge: "new",
    sold: false,
    ebayUrl: "https://www.ebay.com/itm/397936426626",
    added: "2026-05-10",
    description: "",
  },
  {
    id: 9,
    name: "Vintage Emergency Light Bar",
    era: "1980s",
    type: "other",
    price: 8,
    imgs: ["img/finds/lightbar.vintage-emergency.red.amber.jpg"],
    emoji: "🚨",
    badge: "rare",
    sold: false,
    ebayUrl: "https://www.ebay.com/itm/YOUR_LISTING_ID",
    added: "2026-02-27",
    description: "",
  },
];
